package main;

import terminal.C64VideoMatrix;

import javax.swing.*;
import java.awt.*;
import java.io.File;

public class ActionPanel
{
    private JPanel thisPanel;
    private JButton upButton;
    private JButton downButton;
    private JButton openButton;
    private JLabel fileName;
    private FileMapper mapper;

    private C64VideoMatrix matrix;

    public ActionPanel (final C64VideoMatrix mat)
    {
        matrix = mat;

        upButton.addActionListener(e ->
        {
        });

        downButton.addActionListener(e ->
        {
        });

        openButton.addActionListener(e ->
        {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
            int result = fileChooser.showOpenDialog(thisPanel);
            if (result == JFileChooser.APPROVE_OPTION)
            {
                File selectedFile = fileChooser.getSelectedFile();
                fileName.setText(selectedFile.getAbsolutePath());
                try
                {
                    mapper = new FileMapper (selectedFile, matrix);
                    matrix.setMapper(mapper);
                    mapper.displayLines();
                }
                catch (Exception e1)
                {
                    e1.printStackTrace();
                }
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$ ()
    {
        thisPanel = new JPanel();
        thisPanel.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        thisPanel.add(panel1, BorderLayout.EAST);
        upButton = new JButton();
        upButton.setText("Up");
        panel1.add(upButton, BorderLayout.NORTH);
        downButton = new JButton();
        downButton.setText("Down");
        panel1.add(downButton, BorderLayout.SOUTH);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        thisPanel.add(panel2, BorderLayout.WEST);
        openButton = new JButton();
        openButton.setText("Open");
        panel2.add(openButton, BorderLayout.CENTER);
        fileName = new JLabel();
        fileName.setBackground(new Color(-16777216));
        fileName.setForeground(new Color(-16729088));
        fileName.setHorizontalAlignment(0);
        fileName.setOpaque(true);
        fileName.setText("Label");
        thisPanel.add(fileName, BorderLayout.SOUTH);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$ ()
    {
        return thisPanel;
    }
}
