package main;

import c64terminal.C64Panel;

import javax.swing.*;
import java.awt.*;
import java.awt.event.AdjustmentEvent;
import java.awt.event.AdjustmentListener;

public class MainFrame
{
    private JPanel mainPanel;
    private C64Panel c64Panel1;
    private ActionPanel nestedForm1;

    public static void main (String[] args)
    {
        JFrame frame = new JFrame("MainFrame");
        frame.setContentPane(new MainFrame().mainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    private void createUIComponents ()
    {
        mainPanel = new JPanel();
        c64Panel1 = new C64Panel();
        //c64Panel1.setBorder(BorderFactory.createRaisedBevelBorder());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    private void $$$setupUI$$$ ()
    {
        createUIComponents();
        mainPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.add(c64Panel1, BorderLayout.CENTER);

        JScrollBar jb = new JScrollBar(JScrollBar.VERTICAL, 0, 25*8, 0, 0x7ffffff0);
        jb.addAdjustmentListener(new AdjustmentListener()
        {
            @Override
            public void adjustmentValueChanged (AdjustmentEvent e)
            {
                nestedForm1.getMapper().setScrollbarOffset (e.getValue());
                //System.out.println(e.getValue());
            }
        });

        mainPanel.add(jb, BorderLayout.EAST);

        nestedForm1 = new ActionPanel(c64Panel1.getMatrix());
        mainPanel.add(nestedForm1.$$$getRootComponent$$$(), BorderLayout.SOUTH);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$ ()
    {
        return mainPanel;
    }
}
