package main;

import c64terminal.C64Panel;

import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowEvent;
import java.awt.event.WindowFocusListener;

public class MainFrame
{
    private JPanel mainPanel;
    private C64Panel c64Panel1;
    private ActionPanel nestedForm1;
    private JScrollBar scroller;

    public static void main (String[] args)
    {
        JFrame frame = new JFrame("C64 Hexer");
        MainFrame mf = new MainFrame();
        frame.addWindowFocusListener(new WindowFocusListener()
        {
            @Override
            public void windowGainedFocus (WindowEvent e)
            {
                mf.c64Panel1.requestFocus();
            }

            @Override
            public void windowLostFocus (WindowEvent e)
            {
                //mf.c64Panel1.requestFocus();
            }
        });
        frame.setContentPane(mf.mainPanel);
        frame.setResizable(false);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    private void createUIComponents ()
    {
        mainPanel = new JPanel();
        c64Panel1 = new C64Panel();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        setupUI();
    }

    private void setupUI ()
    {
        createUIComponents();
        mainPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.add(c64Panel1, BorderLayout.CENTER);

        scroller = new JScrollBar(JScrollBar.VERTICAL, 0, 0x1000, 0, 0x7ffffff0);
        scroller.addAdjustmentListener(e ->
        {
            nestedForm1.getMapper().setScrollbarOffset (e.getValue());
        });

        mainPanel.add(scroller, BorderLayout.EAST);

        nestedForm1 = new ActionPanel(c64Panel1.getMatrix(), scroller);
        mainPanel.add (nestedForm1.getRootComponent(), BorderLayout.SOUTH);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$ ()
    {
        return mainPanel;
    }
}
