package main;

import c64terminal.C64Panel;

import javax.swing.*;
import java.awt.*;

public class MainFrame
{
    private JPanel mainPanel;
    private C64Panel c64Panel1;

    public static void main (String[] args)
    {
        JFrame frame = new JFrame("MainFrame");
        frame.setContentPane(new MainFrame().mainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    private void createUIComponents ()
    {
        mainPanel = new JPanel();
        c64Panel1 = new C64Panel();
        c64Panel1.setBorder(BorderFactory.createRaisedBevelBorder());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$ ()
    {
        createUIComponents();
        mainPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.add(c64Panel1, BorderLayout.CENTER);
        final ActionPanel nestedForm1 = new ActionPanel(c64Panel1.getMatrix());
        mainPanel.add(nestedForm1.$$$getRootComponent$$$(), BorderLayout.SOUTH);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$ ()
    {
        return mainPanel;
    }
}
